workspace/apps/pidp/src/app/core/services/party.service.ts
workspace/apps/pidp/src/app/features/portal/portal.page.html
workspace/apps/pidp/src/app/features/profile/pages/college-licence-information/college-licence-information.page.html

[Jira](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-146)

PIDP-146 Wordsmithing

---

backend/webapi/Infrastructure/HttpClients/BaseClient.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakAdministrationClient.cs
backend/webapi/Infrastructure/HttpClients/Mail/ChesClient.cs
backend/webapi/Infrastructure/HttpClients/Mail/SmtpEmailClient.cs
backend/webapi/Infrastructure/HttpClients/Plr/PlrClient.cs
backend/webapi/Infrastructure/Services/EmailService.cs

Use LoggerMessage delegates to improve logging performance (and remove all the warnings).

Improve Logging

---

backend/services.plr-intake/Features/Records/Index.cs
backend/webapi/.vscode/launch.json

Luckily, EF Core / NpgSql recognizes `.TrimStart` and can translate it without hassle.

PRIME-273 - Better PLR College Id Matching

---

backend/services.plr-intake/.vscode/settings.json
backend/services.plr-intake/Data/Migrations/20220607015136_Plr_StatusChangeLog.Designer.cs
backend/services.plr-intake/Data/Migrations/20220607015136_Plr_StatusChangeLog.cs
backend/services.plr-intake/Data/PlrDbContext.cs
backend/services.plr-intake/Features/Intake/IntakeService.cs
backend/services.plr-intake/Features/Intake/IntakeServiceOperationTuner.cs
backend/services.plr-intake/Features/Intake/PlrRecordReader.cs
backend/services.plr-intake/Models/StatusChageLog.cs

For now, logs an event whenever `StatusCode` or `StatusReasonCode` is updated.
Also refactored the `PlrRecordReader` into another class and updated the logging to use Logging Extensions.

PIDP-251 - Business Event When PLR Status Changes

---

backend/webapi.tests/Features/AccessRequests/MSTeams.cs
backend/webapi.tests/Features/AccessRequests/SAEforms.cs
backend/webapi.tests/Features/Parties/ProfileStatus.SAEforms.cs
backend/webapi.tests/Features/Parties/ProfileStatus.TestingUtils.cs
backend/webapi.tests/Testing Extensions/FakeItEasyExtensions.cs
backend/webapi.tests/TestingUtils.cs
backend/webapi/Features/AccessRequests/SAEforms.cs
backend/webapi/Features/Parties/ProfileStatus.Model.cs
backend/webapi/Features/Parties/ProfileStatus.cs
workspace/apps/pidp/src/app/features/portal/state/access/access-group.model.ts
workspace/apps/pidp/src/app/features/portal/state/access/sa-eforms-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/sa-eforms-section.model.ts

Pharmacists and Pharm Techs cannot enroll in SA eForms (for now)

PRIME-328 - eForms update

---

backend/webapi/Features/AccessRequests/AccessRequestsController.cs
backend/webapi/Features/AccessRequests/DriverFitness.cs
backend/webapi/Features/AccessRequests/HcimEnrolment.cs
backend/webapi/Features/AccessRequests/SAEforms.cs
backend/webapi/Features/AccessRequests/Uci.cs
backend/webapi/Features/Admin/AdminController.cs
backend/webapi/Features/Admin/MappingProfile.cs
backend/webapi/Features/Admin/PartyDelete.cs
backend/webapi/Features/Admin/PartyIndex.cs
backend/webapi/Infrastructure/Auth/AuthConstants.cs
backend/webapi/Infrastructure/HttpClients/BaseClient.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/IKeycloakAdministrationClient.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakAdministrationClient.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakApiDefinitions.cs
workspace/apps/pidp/src/app/features/admin/pages/parties/parties.page.html
workspace/apps/pidp/src/app/features/admin/pages/parties/parties.page.ts
workspace/apps/pidp/src/app/features/admin/shared/resources/admin-resource.service.ts

Adds button in Admin view to delete all test cards and remove roles from keycloak.
Does not work in prod. Button is hidden in prod, as well.

PIDP-307 - Delete Test Cards

---

backend/webapi/Data/Migrations/20220915001626_NewMSTeams.Designer.cs
backend/webapi/Data/Migrations/20220915001626_NewMSTeams.cs
backend/webapi/Data/PidpDbContext.cs
backend/webapi/Features/AccessRequests/DriverFitness.cs
backend/webapi/Features/AccessRequests/MSTeams.cs
backend/webapi/Features/AccessRequests/MappingProfile.cs
backend/webapi/Infrastructure/HttpClients/Plr/IPlrClient.cs
backend/webapi/Models/AccessRequest.cs
backend/webapi/Models/Address.cs
workspace/apps/pidp/src/app/core/services/document.service.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/clinic-member-form.component.spec.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/clinic-member-form.component.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams-form-state.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams-resource.service.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.model.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.module.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.page.html
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.page.ts
workspace/apps/pidp/src/app/features/history/pages/signed-or-accepted-documents/signed-or-accepted-documents.page.ts

- [PIDP 358 MS Documents in Signed screen](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-358)
- [PIDP 393  Remove DMFT email](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-393)
- [PIDP 389 Finalize FHA MS Teams card](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-389)

Develop to Test

---

workspace/apps/pidp/src/app/features/admin/pages/parties/parties.page.ts

[Jira](https://bcgovmoh.atlassian.net/browse/PIDP-394)

PIDP-394 Admin view after delete

---

workspace/apps/pidp/src/app/core/services/document.service.ts
workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.html
workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.scss
workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.ts
workspace/apps/pidp/src/app/features/history/pages/signed-or-accepted-documents/signed-or-accepted-documents.page.ts
workspace/apps/pidp/src/app/features/portal/state/access/driver-fitness-portal-section.class.ts

[Jira ticket](https://bcgovmoh.atlassian.net/browse/PIDP-391)

PIDP-391 Driver Fitness text

---

workspace/apps/pidp/src/app/features/portal/state/access/ms-teams-portal-section.class.ts

398. MS Teams card text.

---

backend/webapi/Features/Parties/LicenceDeclaration.cs
backend/webapi/Features/Parties/ProfileStatus.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/IKeycloakAdministrationClient.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakAdministrationClient.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakApiDefinitions.cs

Adds CPN to the user in keycloak as an attribute.

PIDP-370 - Add CPN attribute to Keycloak

---

workspace/apps/pidp/src/app/features/profile/pages/personal-information/personal-information.page.ts

[Jira ticket](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-426)

PIDP-426 Snackbar text

---

workspace/apps/pidp/src/app/features/access/pages/ms-teams/clinic-member-form.component.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams-form-state.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.module.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.page.html
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams.page.ts
workspace/apps/pidp/src/app/features/profile/pages/personal-information/personal-information-resource.service.ts

[Jira ticket ](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-418)

PIDP-418 MS Teams Add privacy officer row

---

workspace/apps/pidp/src/app/features/auth/guards/authentication.guard.ts
workspace/apps/pidp/src/app/features/auth/pages/login/login.page.ts

[Jira Ticket](https://bcgovmoh.atlassian.net/browse/PIDP-365)

PIDP-365 Enhanced Admin Routing

---

workspace/apps/pidp/src/app/features/access/pages/prescription-refill-eforms/prescription-refill-eforms.constants.ts
workspace/apps/pidp/src/app/features/auth/pages/login/login.page.html
workspace/apps/pidp/src/app/features/auth/pages/login/login.page.ts
workspace/apps/pidp/src/environments/environment.model.ts
workspace/apps/pidp/src/environments/environment.prod.ts

[Jira](https://bcgovmoh.atlassian.net/browse/PIDP-441)
the support link that we were given is broken. Apparently its in QA on the Prescription Renewal side and will be fixed by the time we go live. TODO double check on Monday that its working

PIDP-441 Prescription Renewal Landing Page update

---

workspace/apps/pidp/src/app/features/access/pages/prescription-refill-eforms/prescription-refill-eforms.constants.ts
workspace/apps/pidp/src/app/features/auth/pages/login/login.page.html
workspace/apps/pidp/src/app/features/auth/pages/login/login.page.ts
workspace/apps/pidp/src/environments/environment.model.ts
workspace/apps/pidp/src/environments/environment.prod.ts

PIDP-441 Prescription Renewal Landing Page update (#130)

---

workspace/apps/pidp/src/app/features/profile/pages/personal-information/personal-information.page.html

[Jira](https://bcgovmoh.atlassian.net/browse/PIDP-308)

PIDP-308 Display College licence related text only to BCSC users

---

backend/webapi/Data/PidpDbContext.cs

Minor cleanup in the DB Context file, removing redundant code and using the newer pattern matching syntax.

Minor Cleanup to Db Context

---

backend/webapi/appsettings.json

This updates the variables for local development to point to the new CHES instance. The remaining work will require updating values in OpenShift.

PRIME-475 - Update CHES Variables

---

workspace/apps/pidp/src/app/features/organization-info/pages/endorsements/endorsements.page.html

[Jira](https://bcgovmoh.atlassian.net/browse/PIDP-489)

PIDP-489 Fix Creating Endorsement Requests

---

backend/webapi/Features/AccessRequests/DriverFitness.cs
backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakApiDefinitions.cs

Role name will be changed in the future

PIDP-478 - Assign Role After DMFT Enrolment

---

backend/webapi/Features/AccessRequests/AccessRequestsController.cs
backend/webapi/Features/AccessRequests/HcimAccountTransfer.cs
backend/webapi/Features/AccessRequests/HcimEnrolment.cs
backend/webapi/Features/AccessRequests/MSTeams.cs
backend/webapi/Features/EndorsementRequests/EndorsementRequestsController.cs
backend/webapi/Features/Endorsements/EndorsementsController.cs
workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness-resource.service.ts
workspace/apps/pidp/src/app/features/access/pages/hcim-account-transfer/hcim-account-transfer-resource.service.ts
workspace/apps/pidp/src/app/features/access/pages/hcim-enrolment/hcim-enrolment-resource.service.ts
workspace/apps/pidp/src/app/features/access/pages/ms-teams/ms-teams-resource.service.ts
workspace/apps/pidp/src/app/features/access/pages/prescription-refill-eforms/prescription-refill-eforms-resource.service.ts
workspace/apps/pidp/src/app/features/access/pages/sa-eforms/sa-eforms-resource.service.ts

updating the access request related routes to fit with the pattern of the rest of the app.

Change AccessRequests Routing

---

backend/webapi/Features/Credentials/BCProvider.Create.cs
backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderApiDefinitions.cs
backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderClient.cs
backend/webapi/Infrastructure/HttpClients/BCProvider/IBCProviderClient.cs
backend/webapi/PidpConfiguration.cs
backend/webapi/appsettings.json

Note: this had to be done programmatically as of this time there is no option to add custom attributes on the Azure portal.

PIDP - 563 Add custom attributes to Azure AD 

---

backend/webapi/Features/CommonDomainEventHandlers/PlrCpnLookupFoundHandlers.cs
backend/webapi/Features/EndorsementRequests/Approve.cs
backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderApiDefinitions.cs

* cpns
* update approve
* fix approve
* reorder
* update CPN found handler
* comment
---------

DEV to TEST

---

backend/webapi/Infrastructure/Services/EmailService.cs
workspace/apps/pidp/src/app/core/services/document.service.ts
workspace/apps/pidp/src/app/features/shell/pages/support-error/support-error.page.html
workspace/apps/pidp/src/app/features/shell/pages/support-error/support-error.page.ts
workspace/apps/pidp/src/environments/environment.prod.ts
workspace/libs/shared/ui/src/lib/components/layout-header-footer/layout-header-footer.component.html
workspace/libs/shared/ui/src/lib/components/layout-header-footer/layout-header-footer.component.ts

PIDP-648 - Replace reference to PIDP inbox to point to CGI

---

workspace/apps/pidp/src/app/features/portal/portal.page.ts

Redirect to BCProvider

---

workspace/apps/pidp/src/app/features/auth/pages/login/login.page.html

PIDP-649 - Add OneHealthID Service to Front Page

---

backend/webapi.tests/Features/Parties/ProfileStatus.PrimaryCareRostering.cs

Fixed backend unit tests

---

workspace/apps/pidp/src/app/features/portal/portal.page.html
workspace/apps/pidp/src/app/features/portal/portal.page.scss
workspace/apps/pidp/src/scss/material/_material-overrides.scss

Changes requested as per comment this morning on [PIDP-655](https://bcgovmoh.atlassian.net/jira/software/c/projects/PIDP/boards/6?modal=detail&selectedIssue=PIDP-655)

PAS Rostering Guide changes

---

workspace/apps/pidp/src/app/features/portal/portal.page.spec.ts
workspace/libs/shared/ui/src/lib/components/form-section/form-section.component.ts

Fix front-end unit tests

---

workspace/apps/pidp/src/app/features/organization-info/pages/endorsements/endorsements.page.html
workspace/apps/pidp/src/app/features/portal/components/expansion-panel/expansion-panel.component.scss
workspace/apps/pidp/src/app/features/portal/components/expansion-panel/expansion-panel.component.ts
workspace/apps/pidp/src/app/features/portal/portal.page.html
workspace/apps/pidp/src/app/features/portal/portal.page.ts
workspace/apps/pidp/src/app/features/profile/pages/personal-information/personal-information.page.html

1. Please delete the following from the current step 6: “Have you already setup Multi-factor authentication (MFA)? If you need help, [download this PDF](https://healthprovideridentityportal.gov.bc.ca/assets/mfa.pdf)”
2. Please add this text to the new step we are making for the MFA Guide, immediately before the final step (currently step 6)
- Title: “Multi-Factor Authentication (MFA) Set-Up Guide”
- Text below title: “If you need help setting up your Multi-Factor Authentication (MFA), please [download this PDF](https://healthprovideridentityportal.gov.bc.ca/assets/mfa.pdf).”
4. On the endorsements page remove hover over question marks.
5. Personal information tile, change `Provide your contact information`. to `Provide your contact information.  Please use an email that you check …

PIDP-662 - Ongoing UAT Feedback from Doctors, MoH, and PHS

---

workspace/apps/pidp/src/app/features/organization-info/pages/endorsements/endorsements.page.html
workspace/apps/pidp/src/app/features/portal/portal.page.html
workspace/apps/pidp/src/app/features/portal/portal.page.scss
workspace/apps/pidp/src/app/features/portal/state/access/driver-fitness-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/hcim-account-transfer-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/hcim-enrolment-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/ms-teams-clinic-member-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/ms-teams-privacy-officer-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/prescription-refill-eforms-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/provider-reporting-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/sa-eforms-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/access/site-privacy-security-checklist-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/organization/administrator-information-portal-section.ts
workspace/apps/pidp/src/app/features/portal/state/organization/endorsements-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/organization/facility-details-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/organization/organization-details-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/profile/college-certification-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/profile/demographics-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/profile/user-access-agreement-portal-section.class.ts
workspace/apps/pidp/src/app/features/portal/state/training/compliance-training-portal-section.class.ts
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/components/user-access-agreement-document/user-access-agreement-document.component.html
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/components/user-access-agreement-document/user-access-agreement-document.component.scss
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/user-access-agreement.page.html
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/user-access-agreement.page.scss

-Also formatted text in UAA and endorsements for mobile and desktop views
-Changed the word "min" to "minute(s)" on all cards

PIDP-663 Endorsement Wordsmithing

---

workspace/libs/shared/ui/src/lib/modules/dashboard/components/dashboard-v2/dashboard-v2.component.html

Fixed the menu not closing

---

workspace/apps/pidp/src/app/features/portal/portal.page.scss

Improved dashboard layout for mobile

PIDP-690 - Improved dashboard layout for mobile

---

workspace/libs/shared/ui/src/lib/modules/dashboard/components/dashboard-v2/dashboard-v2.component.html
workspace/libs/shared/ui/src/lib/modules/dashboard/components/dashboard-v2/dashboard-v2.component.ts

Fix menu disappears on the desktop view

Fix menu disappears on the desktop view

---

workspace/apps/pidp/src/app/features/portal/portal.page.scss
workspace/apps/pidp/src/scss/_pidp-variables.scss
workspace/apps/pidp/src/scss/app.scss
workspace/apps/pidp/src/scss/global.scss
workspace/libs/shared/ui/src/lib/components/layout-header-footer/layout-header-footer.component.scss
workspace/libs/shared/ui/src/lib/components/scroll-target/scroll-target.component.scss

The fix didn't work on the BC Provider Account page.
I did a refactoring to add a variable and it works now.

Scroll to anchor refactoring

---

charts/rabbitmq/rabbitmq-values.yaml

clustering and serviceaccount are enabled in values.yaml file

Making RabbitMQ HA, Performance tuning

---

charts/mailhog/values.yaml
charts/nginx/values.yaml
charts/rabbitmq/README.md
deploy/test_values.yaml

optimize other resources in test env to free up space and run RabbitMQ pods

Deploy RabbitMQ on test env 

---

workspace/apps/pidp/src/app/features/auth/pages/bc-provider-uplift/bc-provider-uplift.page.spec.ts
workspace/apps/pidp/src/app/features/portal/components/portal-card/portal-card.component.spec.ts
workspace/apps/pidp/src/app/features/portal/portal.page.spec.ts

Fix angular unit tests

---

workspace/libs/shared/ui/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.spec.ts
workspace/libs/shared/ui/src/lib/components/dialogs/dialog-default-options.model.ts
workspace/libs/shared/ui/src/lib/components/dialogs/dialog-options.model.ts
workspace/libs/shared/ui/src/lib/pipes/fullname.pipe.ts
workspace/libs/shared/ui/src/lib/pipes/phone.pipe.ts
workspace/libs/shared/utils/src/lib/utils/route-utils.class.ts

Fix lint error in all nx workspaces

Fix lint error in all nx workspaces

---

backend/services.plr-intake.tests/.vscode/settings.json
backend/services.plr-intake.tests/Features/Records/Search.cs
backend/services.plr-intake/Features/Records/Search.cs

Remove leading and trailing spaces when searching for college licence

PIDP-502 - Trim college licence

---

workspace/apps/pidp/src/app/features/portal/portal.page.html
workspace/apps/pidp/src/app/features/portal/portal.page.ts

Endorsements button now becomes available in the PAS guide after the 2nd step is completed.

PIDP-707 Fix Endorsements button in PAS guide

---

charts/rabbitmq/README.md
charts/rabbitmq/rabbitmq-values.yaml

Also added a force boot as there were issues with a failed state of rabbitmq cluster

added rabbitmq plugins shovel, shovel_mgmt, delayed_msg_exch

---

workspace/apps/pidp/src/app/features/auth/pages/login/login.page.scss

- In some small laptop screens (bigger than tablet or mobile) the front page content requires extra refinement

PIDP-738 Front page fix

---

backend/webapi.tests/Features/AccessRequests/MSTeamsClinicMember.cs
backend/webapi.tests/Features/AccessRequests/MSTeamsPrivacyOfficer.cs

Backend tests for MS Teams were failing due to the intersection of three silly things:
1. We weren't specifying an implementation for `IClock`, so a default mock is used instead, generating the default value of December 31st, 1969 for the enrolment date in the email body.
This *should* have failed the tests since we are checking for the Enrolment date by searching for the system's current date localized to Vancouver.
*However*
2. The tests were accidentally passing because the email body also includes the Party's birthdate, which is generated from today's date but **not** localized to Vancouver.
3. It seems our tools pod is now running in another timezone. So today's date localized to Vancouver no longer matches the birthdate in the email body.
It now doesn't do that.

Fix Failing BE Tests

---

workspace/apps/pidp/src/app/core/guards/admin.guard.spec.ts
workspace/apps/pidp/src/app/core/guards/user.guard.spec.ts
workspace/apps/pidp/src/app/features/auth/guards/authentication.guard.spec.ts
workspace/apps/pidp/src/app/features/auth/guards/authorization-redirect.guard.spec.ts
workspace/apps/pidp/src/app/features/auth/guards/redirect-on-feature-flag.guard.spec.ts
workspace/apps/pidp/src/app/features/auth/guards/services/authentication-guard.service.ts
workspace/apps/pidp/src/app/features/auth/guards/services/authorization-redirect-guard.service.ts

Guard unit tests for :
- userGuard
- adminGuard
- authorizationRedirectGuard
- authenticationGuard
- redirectOnFeatureFlagConfigGuard

Front-end guard unit tests

---

backend/services.plr-intake/Infrastructure/HealthChecks/HealthCheckTag.cs
backend/services.plr-intake/Startup.cs
backend/services.plr-intake/plr-intake.csproj

2 HealthCheck endpoints
- `/health/liveness`
- `/health/readiness`

PIDP-775 HealthCheck endpoints for PlrIntake

---

workspace/apps/pidp/src/app/features/access/pages/bc-provider-application/bc-provider-application.page.scss
workspace/apps/pidp/src/app/features/access/pages/bc-provider-edit/bc-provider-edit.page.scss

Error message visibility in BC provider pages

Error message visibility in BC provider pages

---

backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakAdministrationClient.cs

Seems Keycloak is case sensitive with its query strings

Fix Keycloak FindUser

---

workspace/apps/pidp/src/app/features/auth/pages/link-account-confirm/link-account-confirm.page.ts

- Dialog width was growing with the text. Set max-width

PIDP-912 Update dialog width

---

workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.html
workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.scss
workspace/apps/pidp/src/app/features/access/pages/hcim-account-transfer/hcim-account-transfer.page.html
workspace/apps/pidp/src/app/features/access/pages/hcim-account-transfer/hcim-account-transfer.page.scss
workspace/apps/pidp/src/app/features/access/pages/immsbc-eforms/immsbc-eforms.page.html
workspace/apps/pidp/src/app/features/access/pages/immsbc-eforms/immsbc-eforms.page.scss
workspace/apps/pidp/src/app/features/access/pages/ms-teams-clinic-member/ms-teams-clinic-member.page.html
workspace/apps/pidp/src/app/features/access/pages/ms-teams-clinic-member/ms-teams-clinic-member.page.scss
workspace/apps/pidp/src/app/features/access/pages/ms-teams-privacy-officer/ms-teams-privacy-officer.page.html
workspace/apps/pidp/src/app/features/access/pages/ms-teams-privacy-officer/ms-teams-privacy-officer.page.scss
workspace/apps/pidp/src/app/features/access/pages/prescription-refill-eforms/prescription-refill-eforms.page.html
workspace/apps/pidp/src/app/features/access/pages/prescription-refill-eforms/prescription-refill-eforms.page.scss
workspace/apps/pidp/src/app/features/access/pages/provincial-attachment-system/provincial-attachment-system.page.html
workspace/apps/pidp/src/app/features/access/pages/provincial-attachment-system/provincial-attachment-system.page.scss
workspace/apps/pidp/src/app/features/access/pages/sa-eforms/sa-eforms.page.html
workspace/apps/pidp/src/app/features/access/pages/sa-eforms/sa-eforms.page.scss
workspace/apps/pidp/src/app/features/organization-info/pages/endorsements/endorsements.page.html
workspace/apps/pidp/src/app/features/organization-info/pages/endorsements/endorsements.page.scss

Quick fix to update access pages alignment with not having a sidenav any longer

Update look on all Access Pages

---

workspace/apps/pidp/src/app/features/portal/portal.page.html

1. Added ‘the’ to the Welcome to OneHealthID Service.
2.Deleted the sub-title line

pidp-961-small text changes to home page

---

workspace/libs/shared/ui/src/lib/modules/dashboard/components/navbar-menu/nav-menu.ts

In mobile view the side nav is not closing when we click on user access access agreement

side nav for UAA

---

workspace/apps/pidp/src/app/features/faq/pages/help/help.page.html
workspace/apps/pidp/src/app/features/faq/pages/help/help.page.scss
workspace/apps/pidp/src/app/features/faq/pages/help/help.page.ts

- Open external links in new tabs using `uiAnchorDirective`.
- Use the application link from `AppConfig` so the link is updated through environment variables depending on the environment.
- css to display `cursor: pointer` on hover over mfa link.

Help Page refactor

---

workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.ts

the `.subscribe()` was dropped in an update.

Fix Driver Fitness

---

backend/webapi/Features/Parties/ProfileStatus.Model.cs

1. Add keywords for the different cards.

PIDP-1068-Keywords added for all sections of cards.

---

workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.constants.ts
workspace/apps/pidp/src/app/features/access/pages/driver-fitness/driver-fitness.page.ts

- updated DMFT link to working version (thank you Roya)
- removed unused constant

Fix - DMFT update to link

---

backend/webapi/Features/Lookups/Index.cs

For testing purposes, adding a version number to the lookups endpoint.

Add Version to Lookups

---

workspace/apps/pidp/src/app/app.component.spec.ts
workspace/apps/pidp/src/app/core/services/snowplow.service.spec.ts
workspace/apps/pidp/src/app/core/services/snowplow.service.ts
workspace/apps/pidp/src/app/features/access/pages/hcim-account-transfer/hcim-account-transfer.page.spec.ts
workspace/apps/pidp/src/environments/environment.model.ts
workspace/apps/pidp/src/environments/environment.prod.ts

- Change the Snowplow collector to report to the Snowplow Prod environment

Report to Snowplow Production

---

backend/webapi/Features/AccessRequests/AccessRequestsController.cs
backend/webapi/Features/AccessRequests/ProviderReportingPortal.cs
backend/webapi/Features/Parties/ProfileStatus.Model.cs
backend/webapi/Models/PrpAuthorizedLicence.cs

Expand PRP enrolment card to allow Pharmacists.

Expand PRP enrolment card to allow Pharmacists.

---

workspace/apps/pidp/src/app/core/services/document.service.ts
workspace/apps/pidp/src/app/features/access/pages/provider-reporting-portal/provider-reporting-portal.page.html
workspace/apps/pidp/src/app/features/access/pages/provider-reporting-portal/provider-reporting-portal.page.scss

Modified PRP text, heading and css

PIDP-1155-PRP-text

---

workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.html
workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.ts
workspace/apps/pidp/src/app/features/shell/components/portal-dashboard/portal-dashboard.component.html
workspace/apps/pidp/src/app/features/shell/components/portal-dashboard/portal-dashboard.component.ts

- temporarily feature flag until issues are resolved to unblock prod release

Fix/ Feature flag feedback comp

---

workspace/apps/pidp/src/app/features/access/components/access-request-card/access-request-card.component.scss

Make access card smooth by adding a transition css.

OHID-281 Access card smooth transition

---

workspace/apps/pidp/src/app/shared/components/success-dialog/components/dialog-bcprovider-edit.component.ts
workspace/apps/pidp/src/app/shared/components/success-dialog/success-dialog.component.spec.ts
workspace/apps/pidp/src/app/shared/components/success-dialog/success-dialog.component.ts

Fixed dialog bug issues while creating a bc provider account.
Added test cases.

OHID-293 - Fixed dialog bug issues while creating a bc provider account.

---

workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/components/user-access-agreement-document/user-access-agreement-document.component.html
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/components/user-access-agreement-document/user-access-agreement-document.component.scss
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/components/user-access-agreement-document/user-access-agreement-document.component.ts
workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/user-access-agreement-routing.routes.ts

- updated page title
- bold words
- enumeration
- style

OHID-332 UAA update

---

backend/webapi/Data/Migrations/20250604175226_RenameUaaLookup.Designer.cs
backend/webapi/Data/Migrations/20250604175226_RenameUaaLookup.cs
backend/webapi/Models/Lookups/AccessType.cs
workspace/apps/pidp/src/app/core/services/document.service.ts
workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.html

- text update on navbar dropdown
- database migration to rename AccessTypeLookup name only for UAA

OHID-332 text update and rename db lookup
