- backend/webapi.tests/Features/Parties/ProfileStatus.cs
- backend/webapi/Data/Configuration/AccessTypeConfiguration.cs
- backend/webapi/Data/Migrations/20220602043551_AccessTypeTable.Designer.cs
- backend/webapi/Data/Migrations/20220602043551_AccessTypeTable.cs
- backend/webapi/Features/AccessRequests/DriverFitness.cs
- backend/webapi/Features/AccessRequests/HcimAccountTransfer.cs
- backend/webapi/Features/AccessRequests/HcimEnrolment.cs
- backend/webapi/Features/AccessRequests/Index.cs
- backend/webapi/Features/AccessRequests/SAEforms.cs
- backend/webapi/Features/Admin/MappingProfile.cs
- backend/webapi/Features/Parties/MappingProfile.cs
- backend/webapi/Features/Parties/ProfileStatus.Model.cs
- backend/webapi/Features/Parties/ProfileStatus.cs
- backend/webapi/Models/AccessRequest.cs
- backend/webapi/Models/Lookups/AccessType.cs
- workspace/apps/pidp/src/app/features/history/pages/transactions/transaction.model.ts
- workspace/apps/pidp/src/app/features/history/pages/transactions/transactions.page.html
- workspace/libs/shared/data-access/src/lib/models/party.model.ts
Adding a table just for the `AccessType` enum really stuck out like a sore thumb (and we probably should have it in the lookups properly anyways), so this ended up being a bit more than just adding a table.
The "Transactions" view in the FE should be updated in the future to actually use this lookup rather than being hard-coded.
> Update AccessType, Add DB Table

- charts/pidp/values.yaml
Adding script-src CSP to whitelist https://code.jquery.com/jquery-3.6.0.min.js and adding https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css to stype-src
> Adding CSP script-src

- backend/services.plr-intake/Features/Records/RecordsController.cs
- backend/webapi/Extensions/LocalDateExtensions.cs
- backend/webapi/Infrastructure/HttpClients/Plr/PlrClient.cs
So it turns out that there are date formats that C# is happy to coerce into `DateTime`s that JSON cannot de-serialize into. 
So when I changed the PLR API to be a `POST` with a body rather than a `GET` with query strings, license look-up broke when we try to send the birthdate.
> Fix PLR Bug

- backend/webapi/Features/ThirdPartyIntegrations/ThirdPartyintegrationsController.cs
I had originally made this controller inherit from `ControllerBase` (the default ASP.NET base class) for simplicity.
But I forgot to set the media type to `application/json` and set the `[ApiController]` Attribute.
Soooo in order to not forget, I've decided its better to stick to the convention.
> Small updates to DMFT API metadata

- backend/services.plr-intake.tests/Features/Records/Search.cs
- backend/services.plr-intake.tests/Testing Extensions/ContextExtensions.cs
- backend/services.plr-intake/Data/PlrDbContext.cs
- backend/services.plr-intake/Features/Records/Search.cs
The PLR license search now looks at the last 5 digits of the licence number only (as well as trimming leading zeros).
This applies to both the number the user enters as well as the number in PLR.
> PIDP-461 - Better PLR Matching

- backend/webapi/Features/EndorsementRequests/Approve.cs
- backend/webapi/Features/Endorsements/Cancel.cs
- backend/webapi/Models/BusinessEvent.cs
Add or remove the MOA flag to AAD when :
- Removes the MOA flag when the endorsement is cancelled and the MOA has no endorsements for licenced professionals in active standing.
- Adds the MOA flag when the user is unregulated and becomes endorsed by a regulated user in good standing.
> PIDP-592 - MOA Role logic in AAD

- backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderApiDefinitions.cs
- backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderClient.cs
We were using `FullName` from the user to generate Mail Nickname, which adds a space; then were removing the space and declaring that there was an invalid character in the name.
> Remove False Positive Error Log in BCProviderClient

- docker-compose.yml
RabbitMQ official docker images and documentation https://hub.docker.com/_/rabbitmq
The image used `rabbitmq:3-management-alpine`:
- version 3.* of RabbitMQ
- with the "RabbitMQ management" interface accessible locally from the URL http://localhost:15672/
- Alpine is the lightest and most secure Linux distribution for RabbitMQ
Setting default user and password with the default value `guest:guest`
Could be changed or removed.
- Port 5672 used by AMQP (Advanced Message Queuing Protocol)
- Port 15672 used by `RabbitMQ management` UI
Official documentation: https://www.rabbitmq.com/networking.html#ports
> Local docker image for RabbitMQ

- workspace/apps/pidp/src/app/features/profile/pages/user-access-agreement/components/user-access-agreement-document/user-access-agreement-document.component.html
```
Hello, 
Sorry for the short the last minute email, but there’s one final text change for the UAA. 
User Access Agreement 3.0
1.	For Providers registered with a Professional College in BC: 
1.	To only access the System(s) for so long as I am a registrant in good standing with my Professional College and my registration permits me to deliver direct patient care. 
Please delete the word direct.
Thank you!
```
> UAA text update 3

- backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderClient.cs
The user's search sends an error because a user has an apostrophe in its last name.
> fix user search

- workspace/apps/pidp/src/app/features/portal/portal.page.ts
When a user hadnt signed up for BCProvider yet, there was a console error when landing on Portal page which was trying to populate the BCProvider username.
> Fix - Only perform call when bcprovider has been created

- workspace/apps/pidp/src/scss/app.scss
Fix the title positioned underneath the header after scrolling to the anchor.
solution:
https://stackoverflow.com/questions/13614112/using-scrollintoview-with-a-fixed-position-header
> Fix the title positioned underneath the header after scrolling to the anchor.

- .github/workflows/pr-build.yaml
A new job called "get-pr-number" was added. The PR number is equal to github.event.number when opening a PR and its equal to gh pr when pushing to PR. Other jobs have dependency to "get-pr-number"  job
> Fix pr number

- workspace/libs/shared/ui/src/lib/directives/trim.directive.spec.ts
- workspace/libs/shared/ui/src/lib/directives/trim.directive.ts
The backend accepts only a null value or a non-empty string but if the user clicks on the preferred middle name text box an empty value is set and the form can't be saved.
> Fix middle preferred name

- workspace/apps/pidp/src/app/features/portal/portal.page.html
- workspace/apps/pidp/src/app/features/portal/portal.page.ts
- Deleted unused variables from the first iteration of the PAS guide
- Deleted unused css
- Removed checks for Personal info - college licence - uaa status code as the new wizard is in place that forces users to complete those 3 pages before moving on
> Cleanup Portal Page

- workspace/apps/pidp/src/app/features/portal/portal.page.ts
- Use StatusCode enum instead of magic numbers 
- Refactored existing calculation of PAS banner status for improved performance, modularity and readability.
> Refactor Portal Page PAS banner 

- backend/pidp-backend.sln
- backend/services.endorsement-reminder.tests/endorsement-reminder.tests.csproj
- backend/services.endorsement-reminder/Dockerfile
- backend/services.endorsement-reminder/endorsement-reminder.csproj
- backend/tools.do-work/do-work.csproj
- backend/tools.plr-test-data/.vscode/launch.json
- backend/tools.plr-test-data/plr-test-data.csproj
- backend/webapi.tests/.vscode/launch.json
- backend/webapi.tests/pidp.tests.csproj
- backend/webapi/.vscode/launch.json
- backend/webapi/Data/Migrations/20240527105030_DotNet8Upgrade.Designer.cs
- backend/webapi/Data/Migrations/20240527105030_DotNet8Upgrade.cs
- backend/webapi/Data/PidpDbContext.cs
- backend/webapi/Dockerfile
- backend/webapi/Dockerfile.local
- backend/webapi/Infrastructure/Auth/AuthenticationSetup.cs
- backend/webapi/Infrastructure/Queue/MassTransitSetup.cs
- backend/webapi/README.md
- backend/webapi/Startup.cs
- backend/webapi/pidp.csproj
The PLR intake microservice has not been updated as the SAML / mutual auth portion is hard to test ourselves. Once we can get a little bit of the PLR team's time to run the test distributions again we will upgrade.
Developers will need to update their SDK version to 8.0, as well as upgrade Entity Framework CLI:
`dotnet tool update dotnet-ef --global`
> PIDP-493 - Dotnet 8

- docker-compose.yml
The environment variables in `docker-compose.yml` are out of date for running the API in local docker..
> Fix API in local docker

- workspace/apps/pidp/src/app/features/access/components/access-request-card/access-request-card.component.scss
-Access Request cards on desktop and laptop views will appear normally. Scrolling will only appear on smaller screens when the description text is long.
> Fix scrolling inside Access Request Cards

- workspace/apps/pidp/src/app/features/portal/portal.page.html
- workspace/apps/pidp/src/app/features/portal/portal.page.ts
- Merged the three methods into one with a `path` argument that calls the static `routePath(route)`  method for each route.
- Removed `config` as it is no longer used on `portal.page.ts`.
> Refactor Portal page navigation

- backend/webapi/Features/Credentials/BCProvider.Create.cs
Before, the MOH Keycloak treated BC Provider accounts in Dev differently than in Test and Prod. In Dev, the Username was missing the `@IdentityProvider` suffix. 
Recently, the Dev MOH Keycloak was updated to be the same as Test and Prod.
> Fix BC Provider in Dev

- workspace/apps/pidp/src/app/features/portal/state/portal-state.builder.ts
1. Remove feature flag from PRP.
2. The feature will be available for production.
3. Any user with the roles Physician and Pharmacist will be able to see the PRP card.
> Remove feature flag from PRP.

- workspace/apps/pidp/src/app/features/access/pages/bc-provider-edit/bc-provider-edit.page.html
- workspace/apps/pidp/src/app/features/access/pages/bc-provider-edit/bc-provider-edit.page.scss
- workspace/apps/pidp/src/app/features/faq/pages/help/help.page.html
- workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.html
- workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.model.ts
- workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.resource.service.ts
- workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.ts
1. Added Password and MFA reset under profile dropdown.
2. FAQ added for "How do I reset my MFA".
3. Removed space between the BC and provider.
4. Replaced bullets in the reset process steps with numbers.
5. changed Multifactor to multi-factor.
> Pdip 1114 mfa polish

- backend/services.plr-intake/Features/Records/StatusLog.cs
- backend/webapi.tests/Features/CommonEventHandlers/UpdateKeycloakAfterCollegeLicenceUpdated.cs
- backend/webapi/Features/CommonHandlers/CollegeLicenceUpdatedHandler.cs
- backend/webapi/Features/CommonHandlers/PlrCpnLookupFoundHandlers.cs
- backend/webapi/Features/Credentials/BCProvider.Create.cs
- backend/webapi/Features/Credentials/Create.cs
- backend/webapi/Infrastructure/HttpClients/BCProvider/BCProviderApiDefinitions.cs
- backend/webapi/Infrastructure/HttpClients/Keycloak/KeycloakApiDefinitions.cs
- backend/webapi/Infrastructure/HttpClients/Plr/PlrClientDefinitions.cs
- backend/webapi/Infrastructure/Services/PlrStatusUpdateService.cs
The `isPharm` attribute was being set in keycloak due to an architectural misunderstanding. We now set it on the BC Provider account in AAD just like `isMD` and `isRNP`.
> PIDP-1158 - Set isPharm attribute in BC Provider

- workspace/apps/pidp/src/app/features/portal/portal-resource.service.ts
- workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.resource.service.ts
- workspace/apps/pidp/src/app/features/shell/components/navbar-menu/nav-menu.ts
No impact to the user. During uplifting of a BCProvider, potentially during every account linking process, there are 2 GET requests that are made to parties/undefined. Refactor so that these requests are not made since there is no PartyId at the time.
> OHID-140-Refactor account linking requests for undefined PartyID
